export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_SELECTED_ITEM_ID = "SET_SELECTED_ITEM_ID";

export const SET_TRANSACTIONS_DATA = "SET_TRANSACTIONS_DATA";
export const OPEN_ADD_TRANSACTION_DIALOG = "OPEN_ADD_TRANSACTION_DIALOG";
export const CLOSE_ADD_TRANSACTION_DIALOG = "CLOSE_ADD_TRANSACTION_DIALOG";

export const SET_TOP_CATEGORIES_DATA = "SET_TOP_CATEGORIES_DATA";
export const SET_GRAPH_DATA = "SET_GRAPH_DATA";
export const SET_GRAPH_OPTION = "SET_GRAPH_OPTION";

export const SET_TABLE_DATA = "SET_TABLE_DATA";
